{"name": "test_change_user_name", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5", "trace": "@pytest.mark.regression\n    def test_change_user_name():\n>       assert 4 == 5\nE       assert 4 == 5\n\nsomething2_test.py:42: AssertionError"}, "start": 1724852871637, "stop": 1724852871637, "uuid": "eabc9826-a4f5-4db1-a900-b7ed7d0e55fc", "historyId": "c90931fe39f2579ec98715a888798d22", "testCaseId": "c90931fe39f2579ec98715a888798d22", "fullName": "something2_test#test_change_user_name", "labels": [{"name": "tag", "value": "regression"}, {"name": "suite", "value": "something2_test"}, {"name": "host", "value": "MS105M.local"}, {"name": "thread", "value": "7404-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "something2_test"}]}