{"name": "test_change_user_name", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5", "trace": "@pytest.mark.regression\n    def test_change_user_name():\n>       assert 4 == 5\nE       assert 4 == 5\n\ntests/something2_test.py:58: AssertionError"}, "start": 1725261138298, "stop": 1725261138299, "uuid": "23289e95-230a-4f2d-a194-e1078d74a5ac", "historyId": "c259cb851892b66effed72ec816a4e14", "testCaseId": "c259cb851892b66effed72ec816a4e14", "fullName": "tests.something2_test#test_change_user_name", "labels": [{"name": "tag", "value": "regression"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "something2_test"}, {"name": "host", "value": "MS105M.local"}, {"name": "thread", "value": "7214-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.something2_test"}]}